# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionInfo',
            fields=[
                ('AID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=64)),
                ('DelFlag', models.BooleanField(default=True)),
                ('Remark', models.CharField(max_length=256)),
                ('Url', models.CharField(max_length=256)),
                ('AreaName', models.CharField(max_length=64)),
                ('ActionMethodName', models.CharField(max_length=64)),
                ('ControllerName', models.CharField(max_length=64)),
                ('JsFunctionName', models.CharField(max_length=32)),
                ('IconCls', models.CharField(max_length=64)),
                ('IconClassName', models.CharField(max_length=64)),
                ('isShow', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('UID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=64)),
                ('Pwd', models.CharField(max_length=64)),
                ('DelFlag', models.BooleanField(default=False)),
                ('Remark', models.CharField(max_length=256)),
            ],
        ),
    ]
