# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 06:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forecast', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='actioninfo',
            table='actioninfo',
        ),
        migrations.AlterModelTable(
            name='userinfo',
            table='userinfo',
        ),
    ]
