# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 07:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Forecast', '0002_auto_20170919_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='R_UserInfo_Action',
            fields=[
                ('RID', models.AutoField(primary_key=True, serialize=False)),
                ('ActionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Forecast.ActionInfo')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Forecast.UserInfo')),
            ],
        ),
    ]
