# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 07:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forecast', '0003_r_userinfo_action'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='r_userinfo_action',
            table='r_userinfo_action',
        ),
    ]
