# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Forecast', '0004_auto_20170919_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='ModifiedOnTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='Sort',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='SubTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
