//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class actioninfo
    {
        public int ID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string ActionInfoName { get; set; }
        public Nullable<System.DateTime> SubTime { get; set; }
        public Nullable<bool> DelFlag { get; set; }
        public Nullable<System.DateTime> ModifiedOnTime { get; set; }
        public string Remark { get; set; }
        public string Url { get; set; }
        public string AreaName { get; set; }
        public string ActionMethodName { get; set; }
        public string ControllerName { get; set; }
        public string JsFunctionName { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<int> ActionTypeEnum { get; set; }
        public Nullable<int> IconWidth { get; set; }
        public Nullable<int> IconHeight { get; set; }
        public string IconCls { get; set; }
        public string IconClassName { get; set; }
        public Nullable<sbyte> isShow { get; set; }
        public Nullable<int> MethodTypeEnum { get; set; }
    }
}
